# Generated by Django 4.0.3 on 2022-04-05 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=100)),
                ('published_date', models.DateField()),
                ('author', models.CharField(max_length=100)),
                ('publisher', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('book_image', models.ImageField(upload_to='')),
            ],
        ),
    ]
