# Generated by Django 4.0.3 on 2022-04-05 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0002_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='password',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
    ]
