# Generated by Django 4.0.3 on 2022-04-05 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0011_alter_book_author_alter_book_book_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
